[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
paste = "1.0.15"
smallvec = "1.13.2"
thiserror = "2.0.3"
